name: Build Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packaging tools
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev rpm fakeroot

      - name: Build DEB
        run: |
          dpkg-deb --build datasaver-deb datasaver_1.0_all.deb

      - name: Build RPM
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          tar czf ~/rpmbuild/SOURCES/datasaver-1.0.tar.gz datasaver/
          cp datasaver.spec ~/rpmbuild/SPECS/
          rpmbuild -ba ~/rpmbuild/SPECS/datasaver.spec

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: datasaver-packages
          path: |
            datasaver_1.0_all.deb
            ~/rpmbuild/RPMS/noarch/*.rpm
